services:
  persona-engine:
    container_name: izakaya_persona_engine
    build:
      context: ./apps/persona-engine
    environment:
      PORT: 4105
    ports:
      - "4105:4105"

  preview-ui:
    container_name: izakaya_preview_ui
    build:
      context: ./apps/frontend/preview-ui
      args:
        VITE_API_BASE_URL: "http://localhost:4117"
    ports:
      - "5173:8080"
